# Generated by Django 3.1 on 2021-09-23 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20210922_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 8, 1, 17, 864708)),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('php', 'PHP'), ('cpp', 'C++'), ('c#', 'C#'), ('js', 'JavaScript')], max_length=30),
        ),
    ]
